version: '3'
services:
  rserver:
    image: rocker/rstudio:latest
    container_name: rserver_with_vscode
    tty: true
    ports:
      - 8787:8787
    volumes:
      - ./r_data:/home/rstudio/r_data # 호스트와 컨테이너 간 데이터 공유를 위한 볼륨 마운트 설정
  
  jupyterlab:
    container_name: jupyterlab_with_vscode
    image: jupyter/base-notebook
    tty: true
    ports:
      - 8888:8888
      - 6006:6006
      
    environment:
      - JUPYTER_TOKEN=
    volumes:
      - .jupyter:/home/jovyan/.jupyter
      - ./002_IMDB_Movie_Review_Sentiment_Analysis:/home/jovyan/work
      
    command: jupyter lab --ip=0.0.0.0 --allow-root